name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ["3.4.4"]
        sys:
          - os: ubuntu-latest
            rust_toolchain: stable
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/ruby_install
        with:
          ruby-version: ${{ matrix.ruby-version }}
          os: ${{ matrix.sys.os }}
      - name: Clippy
        run: cargo clippy --all-features --verbose -- -D warnings
      - name: Build
        run: cargo build --all-features --verbose
      - name: Run tests
        run: cargo test --all-features --verbose
